#!/usr/bin/env bash
# Configure Nginx so that /redirect_me is redirecting to another page.

sudo apt-get update
sudo apt-get install -y nginx

sudo ufw allow 'Nginx HTTP'

echo "Hello World!" | sudo tee /var/www/html/index.html

buffer="server_name _;\n\trewrite ^\/redirect_me https:\/\/twitter.com\/rash0x6964 permanent;"
sudo sed -i "s/server_name _;/$buffer/" /etc/nginx/sites-enabled/default

sudo service nginx restart
