#!/usr/bin/env bash
# Setup Nginx and apply some config

sudo apt-get update
sudo apt-get install -y nginx

sudo ufw allow 'Nginx HTTP'

echo "Hello World!" | sudo tee /var/www/html/index.html

buffer="server_name _;\n\trewrite ^\/redirect_me https:\/\/twitter.com\/rash0x6964 permanent;"
sudo sed -i "s/server_name _;/$buffer/" /etc/nginx/sites-enabled/default

echo "Ceci n'est pas une page" | sudo tee /var/www/html/404.html

buffer_2="listen 80 default_server;\n\terror_page 404 \/404.html;\n\tlocation = \/404.html {\n\t\troot \/var\/www\/html;\n\t\tinternal;\n\t}"
sudo sed -i "s/listen 80 default_server;/$buffer_2/" /etc/nginx/sites-enabled/default

buffer_3="server_name _;\n\tadd_header X-Served-By \$hostname;"
sudo sed -i "s/server_name _;/$buffer_3/" /etc/nginx/sites-enabled/default

sudo service nginx restart
