#!/usr/bin/env bash
# Install/configure HAproxy on your lb-01 server.

sudo apt-get -y update

sudo apt-get -y install --no-install-recommends software-properties-common
sudo add-apt-repository -y ppa:vbernat/haproxy-2.8
sudo apt-get -y install haproxy=2.8.\*

haproxy_config="
frontend web-frontend
    bind *:80
    mode http
    default_backend web-backend

backend web-backend
    balance roundrobin
    server 439939-web-01 54.236.54.151:80 check
    server 439939-web-02 34.229.189.161:80 check
"

sudo tee -a /etc/haproxy/haproxy.cfg > /dev/null <<< "$haproxy_config"
sudo tee -a /etc/default/haproxy > /dev/null <<< "ENABLED=1"

sudo systemctl restart haproxy
