#!/usr/bin/env bash
# Install/configure HAproxy on your lb-01 server.

sudo apt-get -y update

sudo apt-get -y install --no-install-recommends software-properties-common
sudo add-apt-repository -y ppa:vbernat/haproxy-2.8
sudo apt-get -y install haproxy=2.8.\*

haproxy_config=="frontend web-frontend
    bind *:80
    mode http
    default_backend web-backend

backend web-backend
   balance roundrobin
   server 439939-web-01 100.25.183.130:80 check
   server 439939-web-02 45.172.78.35:80 check"

sudo chmod go+w /etc/haproxy/haproxy.cfg
echo "$haproxy_config" | sudo tee -a /etc/haproxy/haproxy.cfg > /dev/null
sudo chmod go+w /etc/default/haproxy
echo "ENABLED=1" | sudo tee -a /etc/default/haproxy > /dev/null

sudo systemctl restart haproxy
