#!/usr/bin/env bash
# Bash script that pings an IP address passed as an argument

if [ $# -eq 0 ]; then
  script_name=$(basename "$0")
  echo "Usage: $script_name {IP_ADDRESS}"
else
  ping -c 5 "$1"
fi
